#!/usr/bin/env node
/**
 * Bundle the Source Application READ surface from the library's own TypeScript
 * source (`src/lib/ergo/*`) into ONE Node-loadable ESM module:
 *
 *     mcp/_generated/lib.bundle.mjs
 *
 * Run: `npm run build:mcp`  (or `node mcp/build.mjs`).
 *
 * Why a build step instead of a hand-port: the published `dist/` is not bare-Node
 * loadable (extensionless relative imports, the `reputation-system` Svelte entry,
 * a `dompurify` DOM dep). esbuild compiles the TS, inlines our pure deps, and
 * rewrites the browser-only edges so the SAME `src` logic runs headless — no
 * second copy of the read logic to drift.
 *
 * Aliases / externals:
 *   - `reputation-system`     → `reputation-system/node` (the headless entry that
 *                               exports searchBoxes / getTimestampFromBlockId), kept
 *                               EXTERNAL so reads resolve the SAME installed package
 *                               that writes.mjs uses at runtime (no drift, no giant
 *                               tx-builder graph inlined).
 *   - `$app/environment`      → _stubs/app-environment.mjs (`browser = false`).
 *   - `dompurify`             → _stubs/dompurify.mjs (passthrough; data is read-only
 *                               and only JSON.parsed, never rendered — see the stub).
 *   Everything else (our src, @fleet-sdk/core, @scure/base, @noble/hashes) is
 *   inlined, so the bundle is self-contained apart from `reputation-system/node`.
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const r = (p) => resolve(here, p);

// Redirect the bare `reputation-system` import to its Node entry AND mark it
// external, so the emitted bundle keeps `import ... from "reputation-system/node"`
// and Node resolves it from node_modules at runtime (same package as writes.mjs).
const reputationNodeExternal = {
  name: 'reputation-system-node-external',
  setup(b) {
    b.onResolve({ filter: /^reputation-system$/ }, () => ({
      path: 'reputation-system/node',
      external: true
    }));
    b.onResolve({ filter: /^reputation-system\/node$/ }, () => ({
      path: 'reputation-system/node',
      external: true
    }));
  }
};

await build({
  entryPoints: [r('_entry.mjs')],
  outfile: r('_generated/lib.bundle.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  legalComments: 'none',
  banner: {
    js: '// AUTO-GENERATED by mcp/build.mjs from src/lib/ergo/*. Do not edit by hand.\n// Regenerate with: npm run build:mcp'
  },
  alias: {
    '$app/environment': r('_stubs/app-environment.mjs'),
    dompurify: r('_stubs/dompurify.mjs')
  },
  plugins: [reputationNodeExternal]
});

console.log('Built mcp/_generated/lib.bundle.mjs');
